apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-fileshare-volume
  labels:
    usage: sonarqube-fileshare-volume
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-storage-class
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-fileshare-credentials
    shareName: sonarqube-data
    readOnly: false